# sample_workspace_quakejs.yml
version: '3'
services:
  quakejs:
    image: treyyoder/quakejs:latest
    container_name: quakejs
    environment:
      - HTTP_PORT=8080
    ports:
      - "8080:80"
      - "27960:27960"
    restart: unless-stopped
